### ISSUE TITLE
老板，这个库是被你下架了嘛。

### ISSUE THREAD

**Issue by bosscheng** [zhw2590582/rollup-plugin-worker-inline#1]
npm 安装报这个库被下架了。

error Received malformed response from registry for "rollup-plugin-worker-inline". The registry may be down.

**Comment by zhw2590582** [comment]
是的，前天不小心删除了，刚刚又发布了

**Comment by bosscheng** [comment]
谢谢老板

**Comment by bosscheng** [comment]
@zhw2590582 老板，刚试了下，貌似还是不行。 npm 官网也搜索不到。

**Comment by zhw2590582** [comment]
https://www.npmjs.com/package/rollup-plugin-worker-inline

**Comment by bosscheng** [comment]
@zhw2590582  老板可以试下： npm install rollup-plugin-worker-inline

会报：
npm ERR! code ETARGET
npm ERR! notarget No matching version found for rollup-plugin-worker-inline@1.0.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by zhw2590582** [comment]
我试了没问题的
